# Generated by Django 3.0.6 on 2020-05-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
