# Generated by Django 3.0.6 on 2020-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('definition', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('summary', models.CharField(max_length=400)),
            ],
        ),
    ]
